server:
  port: 8081
spring:
  application:
    name: 06-04-2024-WebMVC-UserManagement-mini-2
  datasource:
    password: idfc
    url: jdbc:mysql://localhost:3306/sbms_39
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: zxtj hrfx vkyx pflq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: md7516591@gmail.com
    
app:
 message:
  dupEmail: Duplicate Email
  regSucc: User Registered
  regFail: registeration Failed
  invaildCredentials: Invalid credentials
  pwdMatchErr: New Pwd and Confirm Pwd Should be same
  pwdUpdateErr: Password update is Failed
  oldPwdErr: Given Old Password is Wrong
